# Aliases - lightweight and frequently used
alias g='git' gs='git status' gsw='git switch' add='git add' gc='git commit -m'
alias gp='git push -u origin' gl='git pull' gst='git stash'
alias rb='reboot' pw='poweroff' c='clear' e='exit'
alias gr='go run' gb='go build' gt='go test' gfmt='gofmt -w .'
alias cr='cargo run' cc='cargo check' ct='cargo test' cb='cargo build'
alias b='bun' bd='bun run dev' bi='bun install' ff='fastfetch'
alias ls='eza --all --icons --group-directories-first --color=always'
alias dc='docker-compose up --build'
alias dp='docker ps -sa'
alias dr='docker run -t'
alias py='python3' pyr='python3 main.py'
