"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[character]
format = '$symbol '
success_symbol = '[➜](bold #d4661f)'
error_symbol = '[➜](bold red)'
vicmd_symbol = '[>](bold #d4661f)'

[package]
disabled = true

[directory]
style = 'bold #4a90e2'  # Nice blue
truncation_length = 3
truncate_to_repo = false

[git_branch]
style = 'bold #d4661f'
symbol = ' '

[git_status]
style = '#d4661f'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[cmd_duration]
style = '#d4661f'
min_time = 500

[hostname]
style = 'bold #d4661f'

[username]
style_user = 'bold #d4661f'
style_root = 'bold red'

