# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# ████ BRUTAL VOID - STARSHIP PROMPT CONFIGURATION ████
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#
# Industrial command interface • Raw system diagnostics
# No decoration • No comfort • Pure machine precision
# Cold steel typography • Binary status indicators
#
# "Every prompt is a system status report."
# "The machine acknowledges. The machine executes."
# ─────────────────────────────────────────────────────────

"$schema" = 'https://starship.rs/config-schema.json'

# ▓▓▓ GLOBAL CONFIGURATION - FACTORY SETTINGS ▓▓▓
add_newline = false
command_timeout = 1000
scan_timeout = 30

# ▓▓▓ PROMPT FORMAT - INDUSTRIAL READOUT ▓▓▓
format = """
$fill\
$time\
$line_break\
$all\
$line_break\
=\
$character"""

right_format = """
$status\
$cmd_duration"""

# ▓▓▓ FILL CHARACTER - STRUCTURAL SEPARATOR ▓▓▓
[fill]
symbol = '─'
style = '#333333'

# ▓▓▓ SYSTEM TIME - MACHINE CLOCK ▓▓▓
[time]
disabled = false
format = '[$time]($style)'
style = 'bold white'
time_format = '%H:%M:%S'
utc_time_offset = 'local'

# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# ████████████ COMMAND INTERFACE ████████████
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

[character]
format = '''
$symbol '''
success_symbol = '[](bold white)'
error_symbol = '[](bold white)'
vimcmd_replace_one_symbol = '[](bold white)'
vimcmd_replace_symbol = '[](bold white)'
vimcmd_visual_symbol = '[](bold white)'

# ▓▓▓ SYSTEM USER - OPERATOR IDENTIFICATION ▓▓▓
[username]
style_user = 'bold white'
style_root = 'bold white'
format = '[$user]($style)[@](white)'
disabled = false
show_always = true

# ▓▓▓ MACHINE HOSTNAME - SYSTEM IDENTIFIER ▓▓▓
[hostname]
ssh_only = false
format = '[$hostname]($style)[|](white)'
style = 'bold white'
disabled = false

# ▓▓▓ DIRECTORY PATH - FILESYSTEM LOCATION ▓▓▓
[directory]
style = 'bold white'
format = ' [$path]($style)[$read_only]($read_only_style)'
truncation_length = 1
truncate_to_repo = false
truncation_symbol = ''
read_only = '[▓RO▓]'
read_only_style = 'bold white'
home_symbol = '~'
use_os_path_sep = true

# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# ████████████ VERSION CONTROL SYSTEM ████████████
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

[git_branch]
style = 'bold white'
symbol = ''
format = ' [$symbol$branch(:$remote_branch)]($style) '
truncation_length = 20
truncation_symbol = '…'
only_attached = false
always_show_remote = false
ignore_branches = []

[git_commit]
style = 'bold white'
format = '[\($hash$tag\)]($style)'
commit_hash_length = 7
tag_symbol = '▓TAG▓'
tag_disabled = false
only_detached = true

# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# ████████████ SYSTEM DIAGNOSTICS ████████████
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

[cmd_duration]
style = 'bold white'
min_time = 500
format = '[▓$duration▓]($style)'
show_milliseconds = true
show_notifications = false
min_time_to_notify = 45000

[status]
style = 'bold white'
symbol = '| ERR | '
success_symbol = ''
not_executable_symbol = '▓NOEXEC▓'
not_found_symbol = '▓404▓'
sigint_symbol = '▓SIGINT▓'
signal_symbol = '▓SIG▓'
format = '[$symbol$status]($style)'
map_symbol = false
disabled = false
pipestatus = true
pipestatus_separator = '|'
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style)'

[jobs]
style = 'bold white'
symbol = '▓JOBS▓'
number_threshold = 1
symbol_threshold = 1
format = '[$symbol$number]($style)'

# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# ████████████ DEVELOPMENT ENVIRONMENT ████████████
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

[nodejs]
style = 'bold white'
symbol = '| NODE | '
format = '[$symbol($version)]($style)'
version_format = 'v${raw}'
detect_extensions = ['js', 'mjs', 'cjs', 'ts', 'tsx']
detect_files = ['package.json', '.node-version', '.nvmrc']
detect_folders = ['node_modules']
not_capable_style = 'bold white'

[golang]
style = 'bold white'
symbol = '| GO | '
format = '[$symbol($version)]($style)'
version_format = 'v${raw}'
detect_extensions = ['go']
detect_files = [
    'go.mod',
    'go.sum',
    'go.work',
    'glide.yaml',
    'Gopkg.yml',
    'Gopkg.lock',
    '.go-version',
]
detect_folders = ['Godeps']

[python]
style = 'bold white'
symbol = '| PY | '
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
version_format = 'v${raw}'
detect_extensions = ['py']
detect_files = [
    '.python-version',
    'Pipfile',
    '__init__.py',
    'pyproject.toml',
    'requirements.txt',
    'setup.py',
    'tox.ini',
]
detect_folders = []
pyenv_version_name = false
pyenv_prefix = 'pyenv '
python_binary = ['python', 'python3', 'python2']

[rust]
style = 'bold white'
symbol = '| RUST | '
format = '[$symbol($version)]($style)'
version_format = 'v${raw}'
detect_extensions = ['rs']
detect_files = ['Cargo.toml']
detect_folders = []

[docker_context]
style = 'bold white'
symbol = '▓DOCKER▓'
format = '[$symbol$context]($style)'
only_with_files = true
detect_extensions = []
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_folders = []

[kubernetes]
style = 'bold white'
symbol = '▓K8S▓'
format = '[$symbol$context( \($namespace\))]($status)'
disabled = false
detect_extensions = []
detect_files = []
detect_folders = []
contexts = []

# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# ████████████ DISABLED MODULES ████████████
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Efficiency through elimination - No unnecessary data

[package]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[line_break]
disabled = false

# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# END BRUTAL VOID CONFIGURATION
# System prompt configured. Machine interface operational.
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
