cursor #e2e2e2
cursor_text_color #c0c8c9

foreground            #e2e2e2
background            #121414
selection_foreground  #243335
selection_background  #b9c9cc
url_color             #a4ced4

color0   #121414
color1   #f36d9b
color2   #6ad474
color3   #fff572
color4   #92c2c9
color5   #395d62
color6   #a4ced4
color7   #d1dcde
color8   #7f8889
color9   #ff9fc0
color10  #a5fead
color11  #fff8a5
color12  #bce3e9
color13  #d6f9ff
color14  #e5fbff
color15  #f8feff
