cursor #e2e2e5
cursor_text_color #c2c7ce

foreground            #e2e2e5
background            #121416
selection_foreground  #24323d
selection_background  #bac8d7
url_color             #a4cbed

color0   #121416
color1   #ff729d
color2   #76ed85
color3   #fff772
color4   #8dbae1
color5   #2f506d
color6   #a4cbed
color7   #e9f1f8
color8   #8e949a
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #bcdfff
color13  #c8e5ff
color14  #dbeeff
color15  #f8fcff
