cursor #eedfdf
cursor_text_color #d8c1c2

foreground            #eedfdf
background            #191212
selection_foreground  #47272b
selection_background  #ecbabe
url_color             #ffb2ba

color0   #191212
color1   #ff7274
color2   #9cff7f
color3   #ffe372
color4   #f29aa3
color5   #76343b
color6   #ffb2ba
color7   #ffeff1
color8   #a5999a
color9   #ff9fa0
color10  #baffa5
color11  #ffeda5
color12  #ffbdc4
color13  #ffc9ce
color14  #ffdcdf
color15  #fff8f9
