cursor #121d20
cursor_text_color #3d494c

foreground            #121d20
background            #f0fbff
selection_foreground  #ffffff
selection_background  #a8cbe2
url_color             #006879

color0   #091518
color1   #790029
color2   #005f09
color3   #998e00
color4   #006d7f
color5   #91ccd6
color6   #006879
color7   #202323
color8   #000203
color9   #c63c56
color10  #008c0d
color11  #a59a00
color12  #087a8e
color13  #91ccd6
color14  #4e929d
color15  #b7bebf
