cursor #f7dcde
cursor_text_color #dac0c2

foreground            #f7dcde
background            #1d1011
selection_foreground  #4c251e
selection_background  #f6b8ac
url_color             #ffb2ba

color0   #1d1011
color1   #ff7274
color2   #9cff7f
color3   #ffe372
color4   #f29aa3
color5   #76343b
color6   #ffb2ba
color7   #ffeff1
color8   #494041
color9   #ff9fa0
color10  #baffa5
color11  #ffeda5
color12  #ffbdc4
color13  #ffc9ce
color14  #ffdcdf
color15  #fff8f9
