font_family monospace
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

modify_font cell_height 0px

background_opacity 0.70
window_padding_width 10
window_margin_width 0
hide_window_decorations yes
dim_opacity 1.0

cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

scrollback_lines 10000
scrollback_pager_history_size 10
wheel_scroll_multiplier 5.0

enable_audio_bell no
visual_bell_duration 0.0

copy_on_select no
strip_trailing_spaces never

open_url_with default

clipboard_control write-clipboard write-primary read-clipboard-ask
clipboard_max_size 512

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2

repaint_delay 10
input_delay 3
sync_to_monitor yes

shell_integration enabled
allow_remote_control no
confirm_os_window_close 0

remember_window_size yes

include dank-theme.conf
include dank-tabs.conf
