theme = "dracula"
client_id = "f4b06b625b8c45eb894e7d6b0f7aa68e"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album}
{metadata}"""
playback_metadata_fields = ["repeat", "shuffle", "volume", "device"]
tracks_playback_limit = 200
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
pause_icon = "▶"
play_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
cover_img_pixels = 128
enable_media_control = true
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
default_device = "monky"
seek_duration_secs = 5
sort_artist_albums_by_type = false

[layout]
playback_window_position = "Bottom"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "monky"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
autoplay = true
